
FROM python:3.9.2-slim AS build-env
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt  
COPY . /app

FROM gcr.io/distroless/python3
RUN python --version
COPY --from=build-env /app /app
COPY --from=build-env /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.9/site-packages

CMD ["app.py"]