apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "colors.fullname" . }}
  labels:
    {{- include "colors.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "colors.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen:
      activeService: {{ include "colors.fullname" . }}
      previewService: {{ include "colors.fullname" . }}-preview
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "colors.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP